evaluate-commands %sh{
    plugins="$kak_config/bundle"
    mkdir -p "$plugins"
    [ ! -e "$plugins/kak-bundle" ] && \
        git clone -q https://codeberg.org/jdugan6240/kak-bundle "$plugins/kak-bundle"
    printf "%s\n" "source '$plugins/kak-bundle/rc/kak-bundle.kak'"
}
bundle-noload kak-bundle https://codeberg.org/jdugan6240/kak-bundle

bundle splash.kak https://github.com/ftonneau/splash.kak
bundle insert-indicator https://github.com/casonadams/insert-indicator
bundle fzf.kak https://github.com/andreyorst/fzf.kak
bundle kakoune-sudo-write https://github.com/occivink/kakoune-sudo-write
bundle kakoune-palette https://github.com/delapouite/kakoune-palette


bundle byline.kak https://github.com/evanrelf/byline.kak %{
    require-module "byline"
}

bundle kakboard https://github.com/lePerdu/kakboard %{
    hook global WinCreate .* %{ kakboard-enable }
}

bundle auto-pairs.kak https://github.com/alexherbo2/auto-pairs.kak %{
    hook global WinCreate .* %{ enable-auto-pairs }
}

bundle kaktree https://github.com/andreyorst/kaktree %{
    set-option global kaktree_double_click_duration '0.5'
    set-option global kaktree_indentation 1
    set-option global kaktree_dir_icon_open  '▾ 🗁 '
    set-option global kaktree_dir_icon_close '▸ 🗀 '
    set-option global kaktree_file_icon      '⠀⠀🖺'
    
    hook global WinSetOption filetype=kaktree %{
        remove-highlighter buffer/numbers
        remove-highlighter buffer/matching
        remove-highlighter buffer/wrap
        remove-highlighter buffer/show-whitespaces
    }
}


bundle powerline.kak https://github.com/andreyorst/powerline.kak %{
    require-module powerline

	powerline-start
    powerline-format global 'git bufname filetype mode_info line_column position'
    powerline-toggle line_column off
    set-option global powerline_shorten_bufname 'short'
}

bundle langmap.kak https://github.com/andreyorst/langmap.kak

	require-module langmap
    
    set-option global langmap %opt{langmap_ru_jcuken}
    
    map -docstring "toggle layout" global normal '<c-\>' ':toggle-langmap<ret>'
    map -docstring "toggle layout" global insert '<c-\>' '<a-;>:toggle-langmap<ret>'
    map -docstring "toggle layout" global prompt '<c-\>' '<a-;>:toggle-langmap prompt<ret>'


eval %sh{kak-lsp}
hook global WinSetOption filetype=(rust|python|c|cpp|markdown|javascript|typescript|ruby) %{
    lsp-enable-window
}




hook global User bundle-after-install %{
  quit!
}




set-option global startup_info_version 99999999

set-option global indentwidth 4
set-option global tabstop 4
set-option global scrolloff 3,3
set-option global ui_options ncurses_assistant=cat

hook global WinCreate .* %{ try %{
    add-highlighter buffer/numbers  number-lines -hlcursor
    add-highlighter buffer/matching show-matching
    add-highlighter buffer/wrap     wrap -word -indent
    add-highlighter buffer/todo     regex \b(TODO|FIXME|XXX|NOTE)\b 0:default+rb
}}

hook global WinCreate ^[^*]+$ %{ git show-diff }
hook global BufWritePost ^[^*]+$ %{ git update-diff }

map global normal <c-p> ': fzf-mode<ret>'
map global normal <t> ': terminal zsh<ret>'
